### ISSUE TITLE
Add COLCON_IGNORE to the generated documentation?

### ISSUE THREAD

**Issue by damien-robotsix** [ros-infrastructure/rosdoc2#125]
I don't know if it is a wrong usage I make but the created documentation files appear in my ros2_workspace. When I try to colcon build again it complains about duplicate packages names since they are also found in the documentation.

A simple COLCON_IGNORE file would avoid that I think.

**Comment by rkent** [comment]
Can you please give the full path to the documentation folders that are detected as duplicate packages by colcon?

**Comment by damien-robotsix** [comment]
In my ROS workspace it got

ERROR:colcon:colcon build: Duplicate package names not supported:
- _package_name_:
  - docs_build/package_name/package_name/wrapped_sphinx_directory/standard_docs/original
  - src/package_name
  
  I was working on a custom package but using default rosdoc2 configuration.
