### ISSUE TITLE
No such file or directory: 'doxygen'

### ISSUE THREAD

**Issue by jcarpinelli-bdai** [ros-infrastructure/rosdoc2#126]
I'm sure this problem is some form of misconfiguration on my end... but I cannot figure out what I've done wrong! Using the Dev Container in this [example repository](https://github.com/jcarpinelli-bdai/rosdoc2-example), calling `rosdoc2 build -p src/example_package` produces the following error. I believe I have followed the setup instructions in the README. Is there anything glaring in this [Dockerfile](https://github.com/jcarpinelli-bdai/rosdoc2-example/blob/main/.devcontainer/Dockerfile)?

```sh
[rosdoc2] [INFO] No Doxyfile specified by user, and no Doxyfile found in the package at 'src/example_package/Doxyfile', but a standard include directory was found at 'src/example_package/include', therefore a default Doxyfile will be generated and used.
[rosdoc2] [INFO] Running Doxygen: 'doxygen Doxyfile.rosdoc2' in '/rosdoc2-example/docs_build/example_package/example_package-public-cc-api'
[Errno 2] No such file or directory: 'doxygen'
```

**Comment by rkent** [comment]
I don't see any evidence that you have Doxygen installed in your Dockerfile. You could add ```doxygen``` here:
```
RUN apt-get update && apt-get install -y git make graphviz python3-pip
```
The documentation for rosdoc2 is not in good shape at the moment. I was hoping to improve that, but the main reviewer is on leave at the moment.

**Comment by nuclearsandwich-ai** [comment]
> The documentation for rosdoc2 is not in good shape at the moment. I was hoping to improve that, but the main reviewer is on leave at the moment.

Although we're spread a bit thin, there are other maintainers here as well (and we're working to onboard some new ones).

I don't think it makes sense at the moment for rosdoc2 to be "self hosting" but if there's documentation you'd like to add either to the readme or to a new `doc` folder please do and tag me for review.

**Comment by nuclearsandwich** [comment]
> The documentation for rosdoc2 is not in good shape at the moment. I was hoping to improve that, but the main reviewer is on leave at the moment.

Although we're spread a bit thin, there are other maintainers here as well (and we're working to onboard some new ones).

I don't think it makes sense at the moment for rosdoc2 to be "self hosting" but if there's documentation you'd like to add either to the readme or to a new `doc` folder please do and tag me for review.

**Comment by rkent** [comment]
Hey @nuclearsandwich, on the question of installation instructions, one thing that tripped me up in trying to write up rosdoc2 was how to handle newer Python's issues with ```pip install --user```. The official Python instructions, AFAICT, are to either use pipx, or a virtual environment.  But it seems to me that most of the ROS2 infrastructure stuff uses ```PIP_BREAK_SYSTEM_PACKAGES: 1```  What is ROS2 recommending here? is ```PIP_BREAK_SYSTEM_PACKAGES: 1``` pretty standard in ROS2 user installations?

**Comment by clalancette** [comment]
> Hey @nuclearsandwich, on the question of installation instructions, one thing that tripped me up in trying to write up rosdoc2 was how to handle newer Python's issues with `pip install --user`. The official Python instructions, AFAICT, are to either use pipx, or a virtual environment. But it seems to me that most of the ROS2 infrastructure stuff uses `PIP_BREAK_SYSTEM_PACKAGES: 1` What is ROS2 recommending here? is `PIP_BREAK_SYSTEM_PACKAGES: 1` pretty standard in ROS2 user installations?

Personally, I think that rosdoc2 is kind of special.  Because it is just a pure-python package, and doesn't rely on the rest of the ROS infrastructure, I think we can easily advise people to use virtualenvs here.  I'm reluctant to recommend something like `pipx`, because it feels like the "flavor-of-the-week", and is not the default tool.

**Comment by tfoote** [comment]
We've added doxygen in the stdeb.cfg which will embed it into the debian packages. https://github.com/ros-infrastructure/rosdoc2/blob/24c51d595e4477f11b3929c19e2fb6031936f42e/stdeb.cfg#L3

And that's the recommended way to install to get all dependencies. Closing this as that should solve it. But in general this error is that you're missing doxygen installation on your system.
