### ISSUE TITLE
Trailing double under-scores produces `Anonymous hyperlink mismatch` warning

### ISSUE THREAD

**Issue by aprotyas** [ros-infrastructure/rosdoc2#29]
This issue is mostly seen with macros (such as [`RCPPUTILS_THREAD_ANNOTATION_ATTRIBUTE__`](https://github.com/ros2/rcpputils/blob/cd4ce08ca61a9b641c0a6d6e02a9302de804b0b0/include/rcpputils/thread_safety_annotations.hpp#L44-L48)), since they tend to have trailing double under-scores. The warning reads:
```
line : Error: Anonymous hyperlink mismatch: 1 references but 0 targets.
See "backrefs" attribute for IDs.
```

The problem here is that `exhale` takes identifiers verbatim and throws them into their respective `.rst` files, and double under-scores is used for [anonymous hyperlinking in the restructured text format](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#anonymous-hyperlinks).

The immediate solution is to exclude these identifiers in Doxygen, but I'm opening this issue to track progress on a real fix.

**Comment by clalancette** [comment]
We should rename `RCPPUTILS_THREAD_ANNOTATION_ATTRIBUTE__` to something like `RCPPUTILS_THREAD_ANNOTATION_ATTRIBUTE_IMPL`.  That is standards compliant, and also fixes this particular issue.  Then we can also get rid of the `@cond` that we are currently using.

**Comment by aprotyas** [comment]
Okay, since symbols with double underscores are not standards compliant anyway, I believe this is not a cause for concern anymore.

Feel free to close this issue.

>We should rename `RCPPUTILS_THREAD_ANNOTATION_ATTRIBUTE__` to something like `RCPPUTILS_THREAD_ANNOTATION_ATTRIBUTE_IMPL`. That is standards compliant, and also fixes this particular issue. Then we can also get rid of the `@cond` that we are currently using.

Should I transfer this issue to `rcpputils`?

**Comment by clalancette** [comment]
> Should I open an issue in `rcpputils`? I don't think you can transfer across orgs.

Yeah, I think that makes sense.  I'll close this one and let you open a new one in `rcpputils`.
