### ISSUE TITLE
directory names are stripped of everything in front of '_'

### ISSUE THREAD

**Issue by rkent** [ros-infrastructure/rosdoc2#36]
See, for example, http://docs.ros.org/en/ros2_packages/rolling/api/control_toolbox/api/unabridged_orphan.html#directories

The actual directory is "control_toolbox" but it appears as "toolbox":

>Full API
>Directories
>
>   Directory src
>        Subdirectories
>
>   Directory toolbox
>       Subdirectories

AFAICT this is an issue with breathe, but I have not been able to find any other references to the issue.

**Comment by rkent** [comment]
Actually I found https://github.com/svenevs/exhale/issues/110 which was fixed 2 days ago, so hopefully this will go away soon.

**Comment by aprotyas** [comment]
> AFAICT this is an issue with breathe, but I have not been able to find any other references to the issue.

That was my conclusion about this issue too. I think exhale-0.2.4 fixes this.

**Comment by rkent** [comment]
Yes this now works.
