### ISSUE TITLE
Remove unused --build-directory option

### ISSUE THREAD

**Issue by rkent** [ros-infrastructure/rosdoc2#79]
AFAICT, the --build-directory option is unused. If someone can figure out why it is there, please tell me. If not, we should remove it.

The correct option for the "directory where document builds are done" is --doc-build-directory. I wish it was "--build-directory" but I think that ship has sailed, we should leave it a "--doc-build-directory"

**Comment by tfoote** [comment]
I think that this is a legacy related to #80 where there was both a build directory and then a documentation build directory. If it's unused lets mark it to give a deprecation warning with a declared sunset date to remove it.

**Comment by rkent** [comment]
What would you suggest as a sunset date?

I assume the problem you are trying to prevent is that someone might have scripts that declare -b, and would be broken if it was removed immediately.
